

```{r}
library(latex2exp)
```


```{r}
#the data used below are generated by running the file SIM_THM.R
output_table <- matrix(0,100,13)
m = 100
f = 10
j = 0
for(d in c(50, 100)){
  #for(n in c(400)){
  for(n in c(200,400,600,800,1000)){
    for(c_len in c(400,600,800,1000,1200)){
    #for(c_len in c(800)){
      for(ord in c(1,2)){
        cat(n)
        load(paste0('~/Desktop/pmisimulation4/1102CheckNormal_d',d,'_n',n,'_clen',c_len,'_ord',abs(ord),'.Rdata'))
        power <- rep(0,f)
        power_lr <- rep(0,f)
        power_lr_bp <- rep(0,f)
        for(i in 1:m){
          tmp1 <- PMI_entry_list_36[i,]
          tmp2 <- PMI_entry_list_37[i,]
          power <- power + as.numeric(abs(tmp1)>qnorm(0.975)*PMI_entry_sd_co)
          power_lr <- power_lr + as.numeric(abs(tmp2)>qnorm(0.975)*PMI_entry_sd_lr_co)
          power_lr_bp <- power_lr_bp + as.numeric(abs(tmp2)>qnorm(0.975)*sd_PMI_entry_lr)
        }
        j = j+1
        output_table[j,]<- c(mean(cover_prob), mean(cover_prob_lr) ,mean(cover_prob_lr_2), mean(PMI_entry_sd_co), mean(PMI_entry_sd_lr_co), mean(sd_PMI_entry_lr), mean(power)/m, mean(power_lr)/m, mean(power_lr_bp)/m, d,n,c_len,ord)
      }
    }
  }
}
output_table <- as.data.frame(output_table)
names(output_table) <- c("emp.cp", "lr.cp", "lr.cp.bp", "emp.ci", "lr.ci", "lr.ci.bp","emp.pwr","lr.pwr","lr.pwr.bp", "d","n","T","ord")
output_table
```

## Figure 5 (1st row)

```{r}
x <- c(200,400, 600,800, 1000)
y1 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 251)]
y2 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 451)]
y3 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 651)]
y4 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 851)]
y5 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1051)]
y6 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1251)]

z1 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 251)]
z2 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 451)]
z3 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 651)]
z4 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 851)]
z5 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1051)]
z6 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1251)]

#d = 100
a1 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 301)]
a2 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 501)]
a3 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 701)]
a4 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 901)]
a5 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1101)]
a6 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1301)]

b1 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 301)]
b2 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 501)]
b3 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 701)]
b4 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 901)]
b5 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1101)]
b6 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1301)]

df1 <- data.frame(x, y = y2, Seq_length = as.factor("T = 400"), Method = as.factor("empirical"), d = 50)
df2 <- data.frame(x, y = z2, Seq_length = as.factor("T = 400"), Method = as.factor("lowrank"), d = 50)
df3 <- data.frame(x, y = y3, Seq_length = as.factor("T = 600"), Method = as.factor("empirical"), d = 50)
df4 <- data.frame(x, y = z3, Seq_length = as.factor("T = 600"), Method = as.factor("lowrank"), d = 50)
df5 <- data.frame(x, y = y4, Seq_length = as.factor("T = 800"), Method = as.factor("empirical"), d = 50)
df6 <- data.frame(x, y = z4, Seq_length = as.factor("T = 800"), Method = as.factor("lowrank"), d = 50)
df7 <- data.frame(x, y = y5, Seq_length = as.factor("T = 1000"), Method = as.factor("empirical"), d = 50)
df8 <- data.frame(x, y = z5, Seq_length = as.factor("T = 1000"), Method = as.factor("lowrank"), d = 50)
df9 <- data.frame(x, y = y6, Seq_length = as.factor("T = 1200"), Method = as.factor("empirical"), d = 50)
df10 <- data.frame(x, y = z6, Seq_length = as.factor("T = 1200"), Method = as.factor("lowrank"), d = 50)

####d=100
ef1 <- data.frame(x, y = a2, Seq_length = as.factor("T = 400"), Method = as.factor("empirical"), d = 100)
ef2 <- data.frame(x, y = b2, Seq_length = as.factor("T = 400"), Method = as.factor("lowrank"), d = 100)
ef3 <- data.frame(x, y = a3, Seq_length = as.factor("T = 600"), Method = as.factor("empirical"), d = 100)
ef4 <- data.frame(x, y = b3, Seq_length = as.factor("T = 600"), Method = as.factor("lowrank"), d = 100)
ef5 <- data.frame(x, y = a4, Seq_length = as.factor("T = 800"), Method = as.factor("empirical"), d = 100)
ef6 <- data.frame(x, y = b4, Seq_length = as.factor("T = 800"), Method = as.factor("lowrank"), d = 100)
ef7 <- data.frame(x, y = a5, Seq_length = as.factor("T = 1000"), Method = as.factor("empirical"), d = 100)
ef8 <- data.frame(x, y = b5, Seq_length = as.factor("T = 1000"), Method = as.factor("lowrank"), d = 100)
ef9 <- data.frame(x, y = a6, Seq_length = as.factor("T = 1200"), Method = as.factor("empirical"), d = 100)
ef10 <- data.frame(x, y = b6, Seq_length = as.factor("T = 1200"), Method = as.factor("lowrank"), d = 100)
# Merge the data frames
df.merged <- rbind(df5, df6, df7, df8, df9, df10) #df1, df2, df3, df4, 
df.merged$d = paste0('d = ',df.merged$d)

ef.merged <- rbind( ef5, ef6, ef7, ef8, ef9, ef10) #ef1, ef2, ef3, ef4,
ef.merged$d = paste0('d = ',ef.merged$d)

# Convert the Method factor levels in the data frames
df.merged$Method <- factor(df.merged$Method, levels = c("empirical", "lowrank"), 
                           labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}")))
ef.merged$Method <- factor(ef.merged$Method, levels = c("empirical", "lowrank"), 
                           labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}")))

# Plotting
g1 <- ggplot(df.merged, aes(x, y, colour = Seq_length, linetype = Method)) + 
  geom_line(size=1) + geom_point(size=1.5) + 
  scale_linetype_manual(values = c("solid", "dotdash"), 
                        labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}"))) +
  theme_bw()+theme(axis.text=element_text(size=16, family="Times"),
                   axis.title=element_text(size=16, family="Times"), 
                   legend.text = element_text(size=10),
                   legend.title=element_text(size=16, family="Times"),
                   strip.text = element_text(size=16, family="Times")) + 
  labs(x="Sample Size n", y="Width of Confidence Interval") + facet_wrap(~d)

g2 <- ggplot(ef.merged, aes(x, y, colour = Seq_length, linetype = Method)) + 
  geom_line(size=1) + geom_point(size=1.5) + 
  scale_linetype_manual(values = c("solid", "dotdash"), 
                        labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}"))) +
  theme_bw()+theme(axis.text=element_text(size=16, family="Times"),
                   axis.title=element_text(size=16, family="Times"), 
                   legend.text = element_text(size = 10),
                   legend.title=element_text(size=16, family="Times"),
                   strip.text = element_text(size=16, family="Times")) + 
  labs(x="Sample Size n", y="Width of Confidence Interval")+ facet_wrap(~d)



# pdf(file = "myplot1102kappa1.pdf",
#     width = 16, # The width of the plot in inches
#    height = 5.5) # The height of the plot in inches
g1+g2+plot_layout(ncol=2,guides = 'collect')&
  theme(legend.position='right')
# dev.off()
```


## Figure 5 (2nd row)


```{r}
x <- c(200,400, 600,800, 1000)
y1 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 252)]
y2 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 452)]
y3 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 652)]
y4 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 852)]
y5 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1052)]
y6 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1252)]

z1 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 252)]
z2 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 452)]
z3 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 652)]
z4 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 852)]
z5 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1052)]
z6 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1252)]

#d = 100
a1 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 302)]
a2 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 502)]
a3 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 702)]
a4 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 902)]
a5 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1102)]
a6 <- qnorm(0.975)*output_table$emp.ci[which(output_table$d + output_table$T + output_table$ord == 1302)]

b1 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 302)]
b2 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 502)]
b3 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 702)]
b4 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 902)]
b5 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1102)]
b6 <- qnorm(0.975)*output_table$lr.ci[which(output_table$d + output_table$T + output_table$ord == 1302)]

df1 <- data.frame(x, y = y2, Seq_length = as.factor("T = 400"), Method = as.factor("empirical"), d = 50)
df2 <- data.frame(x, y = z2, Seq_length = as.factor("T = 400"), Method = as.factor("lowrank"), d = 50)
df3 <- data.frame(x, y = y3, Seq_length = as.factor("T = 600"), Method = as.factor("empirical"), d = 50)
df4 <- data.frame(x, y = z3, Seq_length = as.factor("T = 600"), Method = as.factor("lowrank"), d = 50)
df5 <- data.frame(x, y = y4, Seq_length = as.factor("T = 800"), Method = as.factor("empirical"), d = 50)
df6 <- data.frame(x, y = z4, Seq_length = as.factor("T = 800"), Method = as.factor("lowrank"), d = 50)
df7 <- data.frame(x, y = y5, Seq_length = as.factor("T = 1000"), Method = as.factor("empirical"), d = 50)
df8 <- data.frame(x, y = z5, Seq_length = as.factor("T = 1000"), Method = as.factor("lowrank"), d = 50)
df9 <- data.frame(x, y = y6, Seq_length = as.factor("T = 1200"), Method = as.factor("empirical"), d = 50)
df10 <- data.frame(x, y = z6, Seq_length = as.factor("T = 1200"), Method = as.factor("lowrank"), d = 50)

####d=100
ef1 <- data.frame(x, y = a2, Seq_length = as.factor("T = 400"), Method = as.factor("empirical"), d = 100)
ef2 <- data.frame(x, y = b2, Seq_length = as.factor("T = 400"), Method = as.factor("lowrank"), d = 100)
ef3 <- data.frame(x, y = a3, Seq_length = as.factor("T = 600"), Method = as.factor("empirical"), d = 100)
ef4 <- data.frame(x, y = b3, Seq_length = as.factor("T = 600"), Method = as.factor("lowrank"), d = 100)
ef5 <- data.frame(x, y = a4, Seq_length = as.factor("T = 800"), Method = as.factor("empirical"), d = 100)
ef6 <- data.frame(x, y = b4, Seq_length = as.factor("T = 800"), Method = as.factor("lowrank"), d = 100)
ef7 <- data.frame(x, y = a5, Seq_length = as.factor("T = 1000"), Method = as.factor("empirical"), d = 100)
ef8 <- data.frame(x, y = b5, Seq_length = as.factor("T = 1000"), Method = as.factor("lowrank"), d = 100)
ef9 <- data.frame(x, y = a6, Seq_length = as.factor("T = 1200"), Method = as.factor("empirical"), d = 100)
ef10 <- data.frame(x, y = b6, Seq_length = as.factor("T = 1200"), Method = as.factor("lowrank"), d = 100)
# Merge the data frames
df.merged <- rbind(df5, df6, df7, df8, df9, df10) #df1, df2, df3, df4, 
df.merged$d = paste0('d = ',df.merged$d)

ef.merged <- rbind( ef5, ef6, ef7, ef8, ef9, ef10) #ef1, ef2, ef3, ef4,
ef.merged$d = paste0('d = ',ef.merged$d)

# Convert the Method factor levels in the data frames
df.merged$Method <- factor(df.merged$Method, levels = c("empirical", "lowrank"), 
                           labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}")))
ef.merged$Method <- factor(ef.merged$Method, levels = c("empirical", "lowrank"), 
                           labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}")))

# Plotting
g1 <- ggplot(df.merged, aes(x, y, colour = Seq_length, linetype = Method)) + 
  geom_line(size=1) + geom_point(size=1.5) + 
  scale_linetype_manual(values = c("solid", "dotdash"), 
                        labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}"))) +
  theme_bw()+theme(axis.text=element_text(size=16, family="Times"),
                   axis.title=element_text(size=16, family="Times"), 
                   legend.text = element_text(size=10),
                   legend.title=element_text(size=16, family="Times"),
                   strip.text = element_text(size=16, family="Times")) + 
  labs(x="Sample Size n", y="Width of Confidence Interval") + facet_wrap(~d)

g2 <- ggplot(ef.merged, aes(x, y, colour = Seq_length, linetype = Method)) + 
  geom_line(size=1) + geom_point(size=1.5) + 
  scale_linetype_manual(values = c("solid", "dotdash"), 
                        labels = c(TeX("$\\widehat{PMI}$"), TeX("\\widetilde{PMI}"))) +
  theme_bw()+theme(axis.text=element_text(size=16, family="Times"),
                   axis.title=element_text(size=16, family="Times"), 
                   legend.text = element_text(size = 10),
                   legend.title=element_text(size=16, family="Times"),
                   strip.text = element_text(size=16, family="Times")) + 
  labs(x="Sample Size n", y="Width of Confidence Interval")+ facet_wrap(~d)



# pdf(file = "myplot1102kappa2.pdf",
#    width = 16, # The width of the plot in inches
#    height = 5.5) # The height of the plot in inches

g1+g2+plot_layout(ncol=2,guides = 'collect')&
  theme(legend.position='right')
# dev.off()
```



## Figure 1 (Middle)

```{r}
d = 100
n = 1000
c_len = 800
ord = 1
k = 1
load(paste0('~/Desktop/pmisimulation4/1102CheckNormal_d',d,'_n',n,'_clen',c_len,'_ord',abs(ord),'.Rdata'))
p1 <- ggplot()+geom_qq(aes(sample = (PMI_entry_list_37[,k] - pmi_lr_true[k])/PMI_entry_sd_lr_co[k]),size=1.5,color="steelblue",shape=4, show.legend = T)+geom_abline(slope = 1, linetype = 2, color = "Red", linewidth = 1)+theme_bw()+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=15,family="Times"),legend.text=element_text(size=15))+labs(x="Standard Normal Quantiles", y="Empirical Quantiles")

p2 <- ggplot()+geom_qq(aes(sample = (PMI_entry_list_36[,k]-pmi_true[k])/PMI_entry_sd_co[k]),size=1.5,color="darkgreen",shape=4)+geom_abline(slope = 1, linetype = 2, color = "Red", size = 1,show.legend = T)+theme_bw()+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=15,family="Times"),legend.text=element_text(size=15))+labs(x="Standard Normal Quantiles", y="Empirical Quantiles")

p1 + geom_qq(aes(sample = (PMI_entry_list_36[,k]-pmi_true[k])/PMI_entry_sd_co[k]),size=1.5,color="darkgreen",shape=4,show.legend = T)+geom_abline(slope = 1, linetype = 2, color = "Red", size = 1)
# ggsave("myqqplot.pdf", width = 10, height = 10, units = "cm")
```



## Figure 1 (Right)


```{r}
d = 100
n = 1000
c_len = 1200
ord = 1
k = 1
load(paste0('~/Desktop/pmisimulation4/1102CheckNormal_d',d,'_n',n,'_clen',c_len,'_ord',abs(ord),'.Rdata'))
p1 <- ggplot()+geom_qq(aes(sample = (PMI_entry_list_37[,k] - pmi_lr_true[k])/PMI_entry_sd_lr_co[k]),size=1.5,color="steelblue",shape=4)+geom_abline(slope = 1, linetype = 2, color = "Red", linewidth = 1)+theme_bw()+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=15,family="Times"),legend.text=element_text(size=15))+labs(x="Standard Normal Quantiles", y="Empirical Quantiles")

p2 <- ggplot()+geom_qq(aes(sample = (PMI_entry_list_36[,k]-pmi_true[k])/PMI_entry_sd_co[k]),size=1.5,color="darkgreen",shape=4)+geom_abline(slope = 1, linetype = 2, color = "Red", size = 1)+theme_bw()+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=15,family="Times"),legend.text=element_text(size=15))+labs(x="Standard Normal Quantiles", y="Empirical Quantiles")

p1 + geom_qq(aes(sample = (PMI_entry_list_36[,k]-pmi_true[k])/PMI_entry_sd_co[k]),size=1.5,color="darkgreen",shape=4)+geom_abline(slope = 1, linetype = 2, color = "Red", size = 1)
#ggsave("myqqplot2.pdf", width = 10, height = 10, units = "cm")
#ggsave("myqqplot2.png")
```






